### ISSUE TITLE
Added - [Feature Request][Full Array] Feedback in chat

### ISSUE THREAD

**Issue by trilias** [shadoskill/EmptyList_Issues#11]
Feedback in chat who change your clothing make you nude change hair profiles shoe or other stuff

Example:
Nikola Leissa Remove your Top
Nikola Leissa Remove your Pants
Nikola Leissa Change your Outfit to Outfitname
Nikola Leissa Change your Profile to Profilename

**Comment by KinvaraAnarchy** [comment]
This doesn't seem like a bad idea, but it needs to be on a toggle that is defaulted off. It also needs to be on LLInstantMessage.
