### ISSUE TITLE
Added - [Feature Request][Full Array] a Command Channel that have all huds for Toy and Gadget Devs

### ISSUE THREAD

**Issue by trilias** [shadoskill/EmptyList_Issues#14]
A Command Channel that have all huds for Toy and Gadget Devs 
Sold only works if the object owner of the toy or Gadget has the Rights or Hud Public Rights are on 
Noooooooo!!! masterkey to make all shit without the hud owner permission Like someone's Tentacle Rape Trap aka Admin Abuse *peeps certain cat*
Example:
A gun if you hit by his bullet you strip to nude
Or a invisible wall if you go through he strip you also done
and many many other lewd sick shit ^^

**Comment by shadoskill** [comment]
HUD v0.2.10 Will have this feature.
https://wiki.emptylist.co/full_array_api#emptylist_full_array_api
