### ISSUE TITLE
[Full Array][Bug Issue] adds the outfit instead of replacing the outfit

### ISSUE THREAD

**Issue by Aoleth** [shadoskill/EmptyList_Issues#9]
Left my avatar in a public sim while I slept with the array on with a note above my head telling people they can mess with my avatar if they get the hud, when I woke up, I was wearing 3 sets of hair, two of my outfits and I was wearing the planti version of my feet which are only for the bare option as well as my heels, which _should_ be wearing the digi version of my feet along with an alpha to hide the toes. 

Because I was asleep I didn't get to see when or how the outfits got all jumbled but when my partner gets on later tonight we'll try to replicate the issue

**Comment by shadoskill** [comment]
First thing that comes to mind is RLV bug, if you had your viewer minimized while people were messing with your avatar RLV can act very weird, some times it doesn't do commands some times it queues them up etc... 

Needs further testing to learn how to reproduce the issue.

**Comment by KinvaraAnarchy** [comment]
After debugging and looking into this it is an issue on the RLV/RLVa side of things, and not an issue we can resolve. The issue stems from either the window for SL having been minimized, which pauses some RLV functions, or from removing and attaching new outfits/items too quickly.
